INDEX_PAGE = "http://python-forum.org/index.php"
LOGIN_URL = "http://python-forum.org/ucp.php?mode=login"
IP_BAN_URL = "http://python-forum.org/mcp.php?i=ban&mode=ip"
MEMBERS_LIST_URL = "http://python-forum.org/memberlist.php"
NEW_REGISTERED_MEMBERS_URL = "http://python-forum.org/memberlist.php?mode=group&start={}&g=7"
PROFILE_URL = "http://python-forum.org/memberlist.php?mode=viewprofile&u={}"
